name: Omoidasu Web

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [18.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - name: Set the version for ENV
        run: |
          echo "VERSION=${node -p "require('./package.json').version"}" >> $GITHUB_ENV
      - name: Install npm package
        run: |
          npm install
      - name: Build the web project
        run: |
          npm run build
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - name: Create workspace on the remote server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "\
            mkdir -p ~/omoidasu-web; \
            mkdir -p ~/omoidasu-web/dist; \
            "
      - name: Copy the dist files to remote server
        run: |
          scp -rp ./dist/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/omoidasu-web/dist
          scp -rp ./Dockerfile ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/omoidasu-web/
          
      - name: Build Docker image
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "\
            docker build --build-arg API_URL=${{ secrets.API_URL }} . --tag fox20431/omoidasu-web:${{ env.VERSION }} -f ~/omoidasu-web/Dockerfile; \
            "
      - name: Run the Docker image
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "\
            docker run -d --name omoidasu-web -p 9080:80 fox20431/omoidasu-web:${{ env.VERSION }}; \
            "